### ISSUE TITLE
server.ts should be server.js and main.ts should be main.ts

### ISSUE THREAD

**Issue by timothy2005** [SAP/spartacus-docs#1026]
In following document:
there is following part:
`The hosting automation service expects a server.ts file in the dist folder, instead of main.ts in the ssr app folder. To fulfill this requirement, after the build is complete, the dist/APPNAME-server/main.ts file is moved to the dist folder and renamed to server.ts.
`
in which, all the ".ts" should be ".js"

**Comment by dunqan** [comment]
👍 FYI: @gladius-mtl

**Comment by gladius-mtl** [comment]
Fixed 🙂
