### ISSUE TITLE
Wrong hyperlink In Doc <<Architecture>>

### ISSUE THREAD

**Issue by timothy2005** [SAP/spartacus-docs#1133]
In Doc <<[Architecture](https://sap.github.io/spartacus-docs/architecture/)>>, there is a hyperlink on text "**Storefront Features**"
it goes to https://sap.github.io/spartacus-docs/architecture/ , which seems not correct.
I guess it should goes to https://sap.github.io/spartacus-docs/spartacus-features/

**Comment by gladius-mtl** [comment]
Good catch!

Fixed in commit be1c29e9..3eea4944
