### ISSUE TITLE
Doc: Minimum extensions to run spartacus

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus-docs#135]
could be based on our min recipe for testing
https://stash.hybris.com/projects/C3PO/repos/devconfigs/browse/spartacus/build.gradle

or our yenv recipe
https://stash.hybris.com/projects/INFRA/repos/yenv/browse/templates/spartacus

**Comment by RadhepS** [comment]
I spoke with Wei about this list and it seems like it has more extensions than we currently use.

For example "wishlist" or "captchaaddon" are not implemented yet. Additionally, should we be including smartedit if it's the minimum extensions?

**Comment by gladius-mtl** [comment]
No longer relevant
