### ISSUE TITLE
Use npm or use yarn?

### ISSUE THREAD

**Issue by timothy2005** [SAP/spartacus-docs#1360]
Hi,
In [Server-Side Rendering](https://sap.github.io/spartacus-docs/server-side-rendering-in-spartacus/),
There is:
`npm run build:ssr && npm run serve:ssr`

But actually, the whole Spartacus guide recommends we use **_yarn_** instead of **_npm_**.
Why here is using npm, rather than yarn?
Thanks!

**Comment by gladius-mtl** [comment]
You're right, it should be `yarn` 🙂  

Thank you for catching this! The doc has been updated.
