### ISSUE TITLE
Update the "About the B2cStorefrontModule Settings" section in "Building Spartacus"

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus-docs#181]
A few changes occured in the config but the "About the B2cStorefrontModule Settings" wasn't updated. For example:
- site (baseSite) has changed
- i18n has changed

Maybe compare the section to what's in config to be sure nothing else.

**Comment by bgambocjaviniar** [comment]
PR: GH-229

**Comment by gladius-mtl** [comment]
Content added manually to branch `stable/1.x`. This ticket can now be closed.
