### ISSUE TITLE
Back end vs front end configuration

### ISSUE THREAD

**Issue by gladius-mtl** [SAP/spartacus-docs#384]
We need a way to share info about where to configure the various elements of Spartacus, whether it's in the front end or the back end, with links to the relevant documentation. Perhaps it could be a page with a table listing the names of UI elements or features (such as "in stock", "number in stock", search settings, etc etc), and then indicate "front end" or "back end" with links...

**Comment by terryjiang2020** [comment]
Hi there, what's the progress of this one?

**Comment by gladius-mtl** [comment]
Hi Terry 👋 🙂 

This is a case of not having had time to prune the backlog, because this ticket should have been closed a long time ago. The reason being that the architecture has moved on a fair bit since this ticket was created. Also, the documentation repo for Spartacus isn't active anymore, because the relevant documentation has move to the SAP Help Portal. You can see the most recent updates here: https://help.sap.com/docs/SAP_COMMERCE_COMPOSABLE_STOREFRONT?locale=en-US&version=2211
