### ISSUE TITLE
Review Stock Notification

### ISSUE THREAD

**Issue by gladius-mtl** [SAP/spartacus-docs#455]
Do a full review of the Stock Notification doc. See GH-454.

**Comment by shaun-09** [comment]
Hi Matthew, please help to update the **Enabling Stock Notification** section as follows:

> The stock notification feature feature has corresponding CMS-component data in the back end that allows you to enable or disable the feature. The configuration is provided in the B2cStorefrontModule.

**Comment by shaun-09** [comment]
Many thanks! If you are too busy to do so, I can create another issue to update the topics. :-)
