### ISSUE TITLE
Review Notification Preferences

### ISSUE THREAD

**Issue by gladius-mtl** [SAP/spartacus-docs#458]
See GH-457.

**Comment by shaun-09** [comment]
Hi Matthew, please help to update the **Enabling Notification Preferences** section as follows:

> The notification preferences feature has corresponding CMS-component data in the back end that allows you to enable or disable the feature. The configuration is provided in the B2cStorefrontModule.

**Comment by shaun-09** [comment]
I am not sure the phrasing is 100%  accurate, as users may choose to use their own layout configuration in the future. Please advise.

**Comment by gladius-mtl** [comment]
Hi Shaun! Just letting you know that I still have this ticket high on my priority list, and I will resolve it in early January 🙂

**Comment by shaun-09** [comment]
> Hi Shaun! Just letting you know that I still have this ticket high on my priority list, and I will resolve it in early January 🙂

Thank you, Matthew!
