### ISSUE TITLE
Minor version upgrade instructions result in an error.

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus-docs#596]
I've tried the minor version upgrade instruction and it results with this error message:

If I modify `package.json`, and then run `yarn upgrade` as instructed, I get this error:

```
yarn upgrade v1.22.4
error Outdated lockfile. Please run `yarn install` and try again.
```

**Comment by gladius-mtl** [comment]
PR GH-597 wasn't merged, but the suggested updates were copied directly to the `master` branch and published, so this ticket can be closed.
