### ISSUE TITLE
Update storefront build docs for 3.0

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus-docs#771]
Docs page:
https://sap.github.io/spartacus-docs/building-the-spartacus-storefront-from-libraries/

needs to be updated as for 3.0 new dependencies:
- @angular/cli version update to 10.1.0
- nodejs version update do 12.16.1
- check for other missing updates/new steps

**Comment by mirkosoft** [comment]
related to #903

**Comment by gladius-mtl** [comment]
This ticket can be closed because the proposed updates have already been merged from other PRs
